---
platform: darwin
inputs:
  - name: git-roku-guidelines-repo

outputs:
  - name: output

run:
  path: sh
  args:
    - -exc
    - |
      cd git-roku-guidelines-repo
      make pkg
      cd ..
      cp -R git-roku-guidelines-repo/dist/packages/ output/
